config/routes.rb
Rails.application.routes.draw do
  resources :pins do
    member do
      put "like" => 'pins#upvote'      
    end    
  end

  devise_for :users
  root 'pins#index'

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'help' => 'pages#help'
  get 'users/:id' => 'users#show', :as => :profile

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	default_scope -> { order(created_at: :desc) }
	validates 	:description, presence: true, length: { maximum: 500 }

	has_attached_file :image, :styles => { :medium => "250x" }, :default_url => ActionController::Base.helpers.image_path("ghost-image.png")
	validates :image, presence: true
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise 	:database_authenticatable, :registerable,
			:recoverable, :rememberable, :trackable, :validatable
	has_many :pins

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ActionController::Base.helpers.image_path("default-avatar.png")
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

		def configure_permitted_parameters
			devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
			devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:avatar, :name, :email, :password, :current_password, :about, :website) }
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def home
	end

	def about
	end

	def contact
	end

	def help
	end
	
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :correct_user, only: [:edit, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@pins = Pin.page(params[:page]).per(10)
	end

	def show		
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)
		if @pin.save
			redirect_to @pin, notice: "You successfuly created new Pin"
		else
			render 'new'
		end	
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Your Pin has been successfuly updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
			redirect_to root_path		
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back		
	end

	private

		def pin_params
			params.require(:pin).permit(:description, :image)
		end

		def correct_user
			@pin = current_user.pins.find_by(id: params[:id])
			if @pin.nil?
				redirect_to pins_path, notice: "Hey #{@current_user.name}, we are sorry but you are not authorized to perform this action!"
			end
		end

		def find_pin
			@pin = Pin.find_by(id: params[:id])
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		@pins = @user.pins.page(params[:page]).per(10)
		redirect_to root_url and return unless user_signed_in?
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Pinteresting"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

	# Defines different flash messages.
	def bootstrap_class_for(flash_type)
		case flash_type
			when "success"
				"alert-success"   # Green message
			when "error"
				"alert-danger"    # Red message
			when "alert"
				"alert-warning"   # Yellow message
			when "notice"
				"alert-info"      # Blue message
			else
				flash_type.to_s
		end
	end

	# Returns flash messages in the application.
	def flash_messages(opts = {})
		flash.each do |msg_type, message|
			concat(content_tag(:div, message, class: "container alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
				concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
					concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
					concat content_tag(:span, 'Close', class: 'sr-only')
				end)
				concat message
			end)
		end
		nil
	end
	
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer
	.navbar.navbar-default.navbar-fixed-bottom
		.container
			.col-sm-6
				.small.text-muted
					&copy; 
					%b Pinteresting Inc.
					= Date.today.year
			.col-sm-6
				%ul.nav.navbar-nav.pull-right
					%li
						= link_to 'Home', root_path
					%li
						= link_to 'Help', help_path
					%li
						= link_to 'About', about_path
					%li
						= link_to 'Contact', contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-default.navbar-fixed-top
	.container
		.navbar-header
			= link_to 'Pinteresting', root_path, {:id => 'logo', :class => 'navbar-brand'}
		- if user_signed_in?
			%ul.nav.navbar-nav
				%li
					%p.navbar-btn
						= link_to new_pin_path, class: "btn btn-sm btn-default" do
							%span.glyphicon.glyphicon-plus
							%b New Pin
			%ul.nav.navbar-nav.navbar-right
				%li.dropdown
					%a.dropdown-toggle{:href => '#', 'role' => 'button', 'data-toggle' => 'dropdown', 'data-target' => '#'} 
						= image_tag (current_user.avatar.url(:thumb)), { :class => "oNavAvatar" }
						Account
						%b.caret
					%ul.dropdown-menu{'role' => 'menu'}
						%li 
							Signed in as
							%b 
								= current_user.name
						%li.divider
						%li 
							= link_to profile_path(current_user.id) do
								%span.glyphicon.glyphicon-user
								Your Profile
						%li.divider
						%li 
							= link_to edit_user_registration_path do
								%span.glyphicon.glyphicon-tasks
								Settings
						%li 
							= link_to destroy_user_session_path, method: :delete do
								%span.glyphicon.glyphicon-log-out
								Sign Out
		- else
			%ul.nav.navbar-nav.navbar-right
				%li
					= link_to 'Log In', new_user_session_path
				%li
					= link_to 'Sign Up', new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7] <html lang="en" class="no-js ie6">
/[if IE 7 ]    <html lang="en" class="no-js ie7">
/[if IE 8 ]    <html lang="en" class="no-js ie8">
/[if IE 9 ]    <html lang="en" class="no-js ie9">
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
%head
	%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
	/ Mobile viewport optimized
	%meta{:name => "viewport", :content => "width=device-width; initial-scale=1.0; maximum-scale=1.0;"}
	%title= full_title(yield(:title))
	= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
	= javascript_include_tag "application", "data-turbolinks-track" => true
	= csrf_meta_tags
%body
	= render 'layouts/header'
	.container
		= flash_messages
		= yield
		= render 'layouts/footer'

/ = debug(params) if Rails.env.development?

app/views/pages/about.html.haml
- content_for(:title, 'About')

.jumbotron.text-center
	%h1 About

	%p 
		This is basic 
		%b About
		page.

app/views/pages/contact.html.haml
- content_for(:title, 'Contact')

.jumbotron.text-center
	%h1 Contact

	%p 
		This is basic 
		%b Contact
		page.

app/views/pages/help.html.haml
- content_for(:title, 'Help')

.jumbotron.text-center
	%h1 Help

	%p 
		This is basic 
		%b Help
		page.

app/views/pages/home.html.haml
.jumbotron.text-center
	%h1 Welcome to Pinteresting
	%p This is the Pinterest clone application created as part of my self-training on Ruby on Rails.
	%p Want to know more?
	= link_to 'Log In', new_user_session_path, class: 'btn btn-lg btn-default'
	= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-primary'

app/views/pins/_form.html.haml
= form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
			%h3
				= pluralize(@pin.errors.count, "error")
				prevented this Pin from being saved!
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li
						= msg

	.form-group

		= f.text_area :description, placeholder: "Describe your Pin...", class: "form-control"

		%p.help-block
			Upload your Pin by selecting a picture from your hard drive.
		= f.file_field :image

	= f.button (f.object.new_record? ? "Pin it!" : "Update"), class: "btn btn-primary"
	= link_to 'Back', 'javascript:history.go(-1);'

app/views/pins/_pin.html.haml
.box.panel.panel-default
	.PinHolder
		= link_to (image_tag pin.image.url(:medium)), pin
		%span.PinCount
			%span.glyphicon.glyphicon-heart
			= pin.get_upvotes.size
		- if user_signed_in?
			%span.PinLikeWrapper
				= link_to like_pin_path(pin), method: :put, class: 'btn btn-default' do
					%span.small.glyphicon.glyphicon-heart
	.panel-body.text-left
		= pin.description
	.panel-footer
		.row.small
			.col-md-6.text-left
				Submitted by
				%b
					= link_to pin.user.name, profile_path(pin.user)
			.col-md-6.text-right
				= link_to "Show", pin
				- if pin.user == current_user
					= link_to "Edit", edit_pin_path(pin)
					= link_to "Delete", pin, method: :delete, data: { confirm: "You sure?" }

app/views/pins/edit.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit your Pin
			.panel-body
				= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled.infinite-scroll.clearfix
	= render @pins

= paginate @pins

app/views/pins/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 New Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.PinActionBar
				.PinLike
					= link_to like_pin_path(@pin), method: :put, class: 'btn btn-primary' do
						%span.glyphicon.glyphicon-heart
						%b
							Like
					%h5.pull-right
						%span.glyphicon.glyphicon-heart
						%b
							= @pin.get_upvotes.size
			.panel-heading.pin_image
				= image_tag @pin.image.url
			.panel-body
				%p.description
					= @pin.description
			.panel-footer
				.row
					.col-md-6.text-left
						= image_tag (@pin.user.avatar.url(:thumb)), { :class => "oNavAvatar" }
						Submitted by
						%b
							= @pin.user.name
						= time_ago_in_words(@pin.created_at)
						ago
					- if @pin.user == current_user
						.col-md-6.text-right
							= link_to "Edit", edit_pin_path
							= link_to "Delete", pin_path, method: :delete, data: { confirm: "You sure?" }

app/views/shared/_user_info.html.haml
.user-avatar
	= image_tag(@user.avatar.url(:thumb))
%hr
%h1
	= @user.name
%p.text-center
	= link_to "View pins", pins_path, class: "btn btn-xs btn-primary"
%p.text-center
	= @user.website
%p.text-center
	= @user.about

app/views/users/show.html.haml
.panel.panel-body.text-center
	- if user_signed_in?
		.row
			= render 'shared/user_info'
			%hr
		= pluralize(@user.pins.count, "Pin")

#pins.transitions-enabled.infinite-scroll.clearfix
	= render @pins

= paginate @pins